/*
 * Copyright (c) 2006-2020, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author          Notes
 * 2020-04-02     hqfang          first version
 *
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __BOARD_H__
#define __BOARD_H__

#include <main.h>
#include <gc90xx_hal_def.h>
#include "csi_config.h"

#if(defined CONFIG_CONSOLE_DEBUG_UART_EN && CONFIG_CONSOLE_DEBUG_UART_EN == 1U)
extern UART_HandleTypeDef huart_debug;
#endif
void hw_board_init(void);

/*-------------------------- UART CONFIG BEGIN --------------------------*/

/** After configuring corresponding UART or UART DMA, you can use it.
 *
 * STEP 1, define macro define related to the serial port opening based on the serial port number
 *                 such as     #define BSP_USING_UART1
 *
 * STEP 2, according to the corresponding pin of serial port, define the related serial port information macro
 *                 such as     #define BSP_UART1_TX_PIN       "PA9"
 *                             #define BSP_UART1_RX_PIN       "PA10"
 *
 * STEP 3, if you want using SERIAL DMA, you must open it in the RT-Thread Settings.
 *                 RT-Thread Setting -> Components -> Device Drivers -> Serial Device Drivers -> Enable Serial DMA Mode
 *
 * STEP 4, according to serial port number to define serial port tx/rx DMA function in the board.h file
 *                 such as     #define BSP_UART1_RX_USING_DMA
 *
 */
#define BSP_UART3_TX_PIN_AFx    GPIO_AF3//详见GPIO复用功能映射表
#define BSP_UART3_RX_PIN_AFx    GPIO_AF3//详见GPIO复用功能映射表
#define BSP_UART3_TX_PIN        "PC25"
#define BSP_UART3_RX_PIN        "PC26"

#define BSP_UART2_TX_PIN_AFx    GPIO_AF3//详见GPIO复用功能映射表
#define BSP_UART2_RX_PIN_AFx    GPIO_AF3//详见GPIO复用功能映射表
#define BSP_UART2_TX_PIN        "PC20"
#define BSP_UART2_RX_PIN        "PC21"

//#define BSP_UART2_RX_USING_DMA
//#define BSP_UART2_TX_USING_DMA

#define BSP_USING_TIM2
#define BSP_USING_PWM7
#define BSP_USING_PWM7_CH2
#define BSP_USING_TIM7

#ifdef BSP_UART2_RX_USING_DMA
    #define UART2_RX_DMA_INSTANCE       DMA_Channel2
    #define UART2_RX_DMA_CHANNEL        DMA_CHANNEL2
    #define UART2_RX_DMA_RCC            0//RCC_AHBENR_DMAEN
    #define UART2_RX_DMA_IRQ            DMA_IRQn
    #define UART2_RX_SRC_DMA_HS         DMA_HS_UART2_RX
    #define UART2_RX_DST_DMA_HS         DMA_HS_MEMORY
#endif

#ifdef BSP_UART2_TX_USING_DMA
    #define UART2_TX_DMA_INSTANCE       DMA_Channel2
    #define UART2_TX_DMA_CHANNEL        DMA_CHANNEL2
    #define UART2_TX_DMA_RCC            0//RCC_AHBENR_DMAEN
    #define UART2_TX_DMA_IRQ            DMA_IRQn
    #define UART2_TX_SRC_DMA_HS         DMA_HS_MEMORY
    #define UART2_TX_DST_DMA_HS         DMA_HS_UART2_TX
#endif


//#define BSP_UART3_RX_USING_DMA
//#define BSP_UART3_TX_USING_DMA

#ifdef BSP_UART3_RX_USING_DMA
    #define UART3_RX_DMA_INSTANCE       DMA_Channel1
    #define UART3_RX_DMA_CHANNEL        DMA_CHANNEL1
    #define UART3_RX_DMA_RCC            0//RCC_AHBENR_DMAEN
    #define UART3_RX_DMA_IRQ            DMA_IRQn
    #define UART3_RX_SRC_DMA_HS         DMA_HS_UART3_RX
    #define UART3_RX_DST_DMA_HS         DMA_HS_MEMORY
#endif

#ifdef BSP_UART3_TX_USING_DMA
    #define UART3_TX_DMA_INSTANCE       DMA_Channel2
    #define UART3_TX_DMA_CHANNEL        DMA_CHANNEL2
    #define UART3_TX_DMA_RCC            0//RCC_AHBENR_DMAEN
    #define UART3_TX_DMA_IRQ            DMA_IRQn
    #define UART3_TX_SRC_DMA_HS         DMA_HS_MEMORY
    #define UART3_TX_DST_DMA_HS         DMA_HS_UART3_TX
#endif

/*-------------------------- UART CONFIG END --------------------------*/

/*-------------------------- SDIO CONFIG BEGIN --------------------------*/

/** if you want to use sdio you can use the following instructions.
 *
 * STEP 1, open sdio driver framework support in the RT-Thread Settings file
 *
 * STEP 2, define macro related to the sdio
 *                 such as    BSP_USING_SDIO
 *
 * STEP 3, copy your sdio init function from stm32xxxx_hal_msp.c generated by stm32cubemx to the end of board.c file
 *                 such as     void HAL_SD_MspInit(SD_HandleTypeDef* hsd)
 *
 * STEP 4, modify your stm32xxxx_hal_config.h file to support sdio peripherals. define macro related to the peripherals
 *                 such as     #define HAL_SD_MODULE_ENABLED
 *
 * STEP 5, config your device file system or another applications
 *
 */

#define BSP_USING_SDIO

/*-------------------------- SDIO CONFIG END --------------------------*/

/*-------------------------- AUDIO CONFIG BEGIN --------------------------*/
#define BSP_USING_AUDIO

#define BSP_AUDIO_I2S_BCLK_PIN_AFx      GPIO_AF5//详见GPIO复用功能映射表
#define BSP_AUDIO_I2S_WS_PIN_AFx        GPIO_AF5//详见GPIO复用功能映射表
#define BSP_AUDIO_I2S_SD0_PIN_AFx       GPIO_AF5//详见GPIO复用功能映射表
#define BSP_AUDIO_I2S_BCLK_PIN          "PB28"
#define BSP_AUDIO_I2S_WS_PIN            "PB29"
#define BSP_AUDIO_I2S_SD0_PIN           "PB30"

#define BSP_AUDIO_TX_USING_DMA
#ifdef BSP_AUDIO_TX_USING_DMA
    #define AUDIO_TX_DMA_INSTANCE       DMA_Channel2
    #define AUDIO_TX_DMA_CHANNEL        DMA_CHANNEL2
    #define AUDIO_TX_DMA_RCC            0//RCC_AHBENR_DMAEN
    #define AUDIO_TX_DMA_IRQ            DMA_IRQn
    #define AUDIO_TX_SRC_DMA_HS         DMA_HS_MEMORY
    #define AUDIO_TX_DST_DMA_HS         DMA_HS_I2S_TX0
#endif
/*-------------------------- AUDIO CONFIG END --------------------------*/

/*-------------------------- I2C CONFIG BEGIN --------------------------*/
//#define BSP_USING_I2C0
#define BSP_USING_I2C1
//#define BSP_USING_I2C2
//#define BSP_USING_I2C3
/*-------------------------- I2C CONFIG END --------------------------*/

/*-------------------------- CAN CONFIG BEGIN --------------------------*/
#define BSP_USING_CANFD0
//#define BSP_USING_CANFD1
#define BSP_USING_CAN2
//#define BSP_USING_CAN3

/*-------------------------- CAN CONFIG END --------------------------*/

/*-------------------------- VIDEOCAP BEGIN --------------------------*/
#define BSP_USING_VIDEOCAP
/*-------------------------- VIDEOCAP END ----------------------------*/

/*-------------------------- ETH BEGIN --------------------------*/
#define BSP_USING_ETH
#define PHY_USING_LAN8720A
/*-------------------------- ETH END ----------------------------*/

#endif /* __BOARD_H__ */

/******************** end of file *******************/
